### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by quico637** [cruip/open-react-template#110]
quico@cybermovi:~/open-react-template$ npm run dev

> open-pro-next@0.1.0 dev
> next dev

/home/quico/open-react-template/node_modules/next/dist/lib/picocolors.js:130
const { env, stdout } = ((_globalThis = globalThis) == null ? void 0 : _globalThis.process) ?? {};
                                                                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/home/quico/open-react-template/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/quico/open-react-template/node_modules/next/dist/build/output/log.js:55:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by AnshSharma2001** [comment]
Hey, can I work on this issue?
