### ISSUE TITLE
Test Suites: 1 failed, 1 total

### ISSUE THREAD

**Issue by marcolino** [cruip/open-react-template#2]
```
$ export REACT_APP_GA_CODE=123
$ yarn test

FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'parentNode' of undefined

      12 | 
      13 | // Initialize Google Analytics
    > 14 | ReactGA.initialize(process.env.REACT_APP_GA_CODE);
         |         ^
      15 | 
      16 | const trackPage = page => {
      17 |   ReactGA.set({ page });

      at node_modules/react-ga/dist/react-ga.js:926:7
      at _default (node_modules/react-ga/dist/react-ga.js:927:5)
      at Object.initialize (node_modules/react-ga/dist/react-ga.js:267:85)
      at Object.<anonymous> (src/App.js:14:9)
      at Object.<anonymous> (src/App.test.js:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.084s
Ran all test suites.
```

**Comment by pasqualevitiello** [comment]
Please see: https://github.com/react-ga/react-ga/issues/336

**Comment by marcolino** [comment]
As suggested, trying with `ReactGA.initialize(process.env.REACT_APP_GA_CODE, { testMode: true });`
and also setting `export NODE_ENV=test`.
I only get this different error:

    Invariant failed: You should not use <withRouter() /> outside a <Router>

Please state clearly how to perform a successful test of this super nice project...

**Comment by pasqualevitiello** [comment]
I've made a little code refactoring that should fix issues with test https://github.com/cruip/open-react-template/commit/b149e961d9003b43bed3eaa3fcd801313145be66

**Comment by marcolino** [comment]
I did just pull latest commits:
```
$ git log --name-status HEAD^..HEAD
commit 6890792abe2fe07c811724d0c8118730e4e77abf (HEAD -> master, origin/master, origin/HEAD)
Author: pasqualevitiello <pasqualevitiello@gmail.com>
Date:   Sat Apr 18 13:16:38 2020 +0200

    mc

M       src/App.js
```

but unfortunately I keep getting infamous `TypeError: Cannot read property 'parentNode' of undefined` error when testing...

```
$ yarn test
FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'parentNode' of undefined

      12 | 
      13 | // Initialize Google Analytics
    > 14 | ReactGA.initialize(process.env.REACT_APP_GA_CODE);
         |         ^
      15 | 
      16 | const trackPage = page => {
      17 |   ReactGA.set({ page });

      at node_modules/react-ga/dist/react-ga.js:926:7
      at _default (node_modules/react-ga/dist/react-ga.js:927:5)
      at Object.initialize (node_modules/react-ga/dist/react-ga.js:267:85)
      at Object.<anonymous> (src/App.js:14:9)
      at Object.<anonymous> (src/App.test.js:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.962s
```

I did try to set `NODE_ENV=test` and `NODE_ENV=production` and `REACT_APP_GA_CODE=UA-XXXXX-X` ...

**Comment by pasqualevitiello** [comment]
This was previously pointed out: https://github.com/react-ga/react-ga/issues/336#issuecomment-458191853
