### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by m4nuelschulz** [cruip/open-react-template#52]
When I run "npm install" I get this error code:

npm ERR! code 1
npm ERR! path D:\Desktop\dev\open-react-template\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\Desktop\dev\open-react-template\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\Desktop\\dev\\open-react-template\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Desktop\dev\open-react-template\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Desktop\dev\open-react-template\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Desktop\dev\open-react-template\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Desktop\dev\open-react-template\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Desktop\dev\open-react-template\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Desktop\dev\open-react-template\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Desktop\dev\open-react-template\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Desktop\dev\open-react-template\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Desktop\dev\open-react-template\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Desktop\dev\open-react-template\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Desktop\dev\open-react-template\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Desktop\dev\open-react-template\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Desktop\dev\open-react-template\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\Desktop\dev\open-react-template\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Desktop\\dev\\open-react-template\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Desktop\dev\open-react-template\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\masch\AppData\Local\npm-cache\_logs\2022-01-14T11_49_52_249Z-debug-0.log

Does this project require an older version of node? Is there a quick fix?

**Comment by m4nuelschulz** [comment]
nvm, I will downgrade to node v14 for now.
