### ISSUE TITLE
Uncaught Error: [AppRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

### ISSUE THREAD

**Issue by sangimed** [cruip/open-react-template#59]
Hello, 

I've updated `react-router-dom` from `v5` to `v6` and facing this issue : 
```javscript
Uncaught Error: [AppRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>
    at invariant (index.tsx:19:1)
    at index.tsx:776:1
    at react.development.js:1104:1
    at react.development.js:1067:1
    at mapIntoArray (react.development.js:964:1)
    at mapChildren (react.development.js:1066:1)
    at Object.forEachChildren [as forEach] (react.development.js:1103:1)
    at createRoutesFromChildren (index.tsx:760:1)
    at Routes (index.tsx:339:1)
    at renderWithHooks (react-dom.development.js:14985:1)
```

**Comment by sangimed** [comment]
It seems that the React Router team is working on a backwards compatibility package that allows a smooth migration from ``v5` to `v6` => https://reactrouter.com/docs/en/v6/upgrading/v5.

But maybe any of you has already solved this issue ?
